apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aquarius-rpc-aws-secrets
  namespace: '{{ .Env.NAMESPACE }}'
spec:
  provider: aws
  parameters:
    region: '{{ .Env.AWS_REGION }}'
    objects: |
      - objectName: '/{{ .Env.SECRET_PREFIX }}/aquarius'
        objectType: secretsmanager
        jmesPath:
          - path: 'EVENTS_ECIES_PRIVATE_KEY_RPC'
            objectAlias: EVENTS_ECIES_PRIVATE_KEY
      - objectName: '/{{ .Env.CLUSTER_NAME }}/es-aquarius'
        objectType: secretsmanager
        jmesPath:
          - path: host
            objectAlias: DB_HOSTNAME
          - path: port
            objectAlias: DB_PORT
          - path: username
            objectAlias: DB_USERNAME
          - path: password
            objectAlias: DB_PASSWORD

  # Secrets
  secretObjects:
    - secretName: aquarius-rpc
      type: Opaque
      data:
        - objectName: EVENTS_ECIES_PRIVATE_KEY
          key: EVENTS_ECIES_PRIVATE_KEY
        - objectName: DB_HOSTNAME
          key: DB_HOSTNAME
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
