apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'provider-{{ .Env.CHAIN }}'
  labels:
    chain: '{{ .Env.CHAIN }}'
spec:
  selector:
    matchLabels:
      app: 'provider-{{ .Env.CHAIN }}'
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: 'provider-{{ .Env.CHAIN }}'
    spec:
      serviceAccountName: provider-chain
      volumes:
        - name: provider-chain-secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'provider-chain-{{ .Env.CHAIN }}-aws-secrets'
      containers:
      - name: 'provider-{{ .Env.CHAIN }}'
        image: 'provider-{{ .Env.CHAIN }}-image'
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8030
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8030
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
          - containerPort: 8030
        env:
          - name: PROVIDER_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: 'provider-{{ .Env.CHAIN }}'
                key: PROVIDER_PRIVATE_KEY
          - name: NETWORK_URL
            valueFrom:
              secretKeyRef:
                name: 'provider-{{ .Env.CHAIN }}'
                key: NETWORK_URL
          - name: PROVIDER_ADDRESS
            valueFrom:
              secretKeyRef:
                name: 'provider-{{ .Env.CHAIN }}'
                key: PROVIDER_ADDRESS
          - name: AQUARIUS_URL
            value: '{{ .Env.AQUARIUS_URL }}'
          - name: LOG_LEVEL
            value: INFO
        volumeMounts:
          - name: provider-chain-secrets-store-inline
            mountPath: /mnt/secrets
            readOnly: true
