apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: 'aquarius-chain-{{ .Env.CHAIN }}-aws-secrets'
  labels:
    chain: '{{ .Env.CHAIN }}'
  namespace: '{{ .Env.NAMESPACE }}'
spec:
  provider: aws
  parameters:
    region: '{{ .Env.AWS_REGION }}'
    objects: |
      - objectName: '/{{ .Env.SECRET_PREFIX }}/aquarius'
        objectType: secretsmanager
        jmesPath:
          - path: 'EVENTS_ECIES_PRIVATE_KEY_{{ .Env.CHAIN }}'
            objectAlias: EVENTS_ECIES_PRIVATE_KEY
          - path: 'EVENTS_RPC_{{ .Env.CHAIN }}'
            objectAlias: EVENTS_RPC
          - path: 'OCEAN_ADDRESS_{{ .Env.CHAIN }}'
            objectAlias: OCEAN_ADDRESS
          - path: 'ALLOWED_PUBLISHERS_{{ .Env.CHAIN }}'
            objectAlias: ALLOWED_PUBLISHERS
          - path: 'BFACTORY_BLOCK_{{ .Env.CHAIN }}'
            objectAlias: BFACTORY_BLOCK
          - path: 'METADATA_CONTRACT_BLOCK_{{ .Env.CHAIN }}'
            objectAlias: METADATA_CONTRACT_BLOCK
      - objectName: '/{{ .Env.CLUSTER_NAME }}/es-aquarius'
        objectType: secretsmanager
        jmesPath:
          - path: host
            objectAlias: DB_HOSTNAME
          - path: port
            objectAlias: DB_PORT
          - path: username
            objectAlias: DB_USERNAME
          - path: password
            objectAlias: DB_PASSWORD

  # Secrets
  secretObjects:
    - secretName: 'aquarius-{{ .Env.CHAIN }}'
      type: Opaque
      labels:
        chain: '{{ .Env.CHAIN }}'
      data:
        - objectName: EVENTS_ECIES_PRIVATE_KEY
          key: EVENTS_ECIES_PRIVATE_KEY
        - objectName: EVENTS_RPC
          key: EVENTS_RPC
        - objectName: OCEAN_ADDRESS
          key: OCEAN_ADDRESS
        - objectName: ALLOWED_PUBLISHERS
          key: ALLOWED_PUBLISHERS
        - objectName: BFACTORY_BLOCK
          key: BFACTORY_BLOCK
        - objectName: METADATA_CONTRACT_BLOCK
          key: METADATA_CONTRACT_BLOCK
        - objectName: DB_HOSTNAME
          key: DB_HOSTNAME
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
