apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: 'provider-chain-{{ .Env.CHAIN }}-aws-secrets'
  labels:
    chain: '{{ .Env.CHAIN }}'
  namespace: '{{ .Env.NAMESPACE }}'
spec:
  provider: aws
  parameters:
    region: '{{ .Env.AWS_REGION }}'
    objects: |
      - objectName: '/{{ .Env.SECRET_PREFIX }}/provider'
        objectType: secretsmanager
        jmesPath:
          - path: 'PROVIDER_PRIVATE_KEY_{{ .Env.CHAIN }}'
            objectAlias: PROVIDER_PRIVATE_KEY
          - path: 'NETWORK_URL_{{ .Env.CHAIN }}'
            objectAlias: NETWORK_URL
          - path: 'PROVIDER_ADDRESS_{{ .Env.CHAIN }}'
            objectAlias: PROVIDER_ADDRESS

  # Secrets
  secretObjects:
    - secretName: 'provider-{{ .Env.CHAIN }}'
      type: Opaque
      labels:
        chain: '{{ .Env.CHAIN }}'
      data:
        - objectName: PROVIDER_PRIVATE_KEY
          key: PROVIDER_PRIVATE_KEY
        - objectName: NETWORK_URL
          key: NETWORK_URL
        - objectName: PROVIDER_ADDRESS
          key: PROVIDER_ADDRESS
