apiVersion: v1
kind: Service
metadata:
  name: 'provider-{{ .Env.CHAIN }}'
  labels:
    chain: '{{ .Env.CHAIN }}'
spec:
  type: NodePort
  selector:
    app: 'provider-{{ .Env.CHAIN }}'
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8030
    name: api
